# Generated by Django 3.2.8 on 2022-01-13 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protein', '0005_proteinsegment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidueNumberingScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=20)),
                ('short_name', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residue.residuenumberingscheme')),
            ],
            options={
                'db_table': 'residue_generic_numbering_scheme',
            },
        ),
        migrations.CreateModel(
            name='ResidueGenericNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, max_length=12)),
                ('protein_segment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generic_numbers', to='protein.proteinsegment')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residue.residuenumberingscheme')),
            ],
            options={
                'db_table': 'residue_generic_number',
                'unique_together': {('scheme', 'label')},
            },
        ),
        migrations.CreateModel(
            name='Residue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.SmallIntegerField()),
                ('amino_acid', models.CharField(max_length=1)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.domain')),
                ('generic_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compare', to='residue.residuegenericnumber')),
                ('protein_segment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protein.proteinsegment')),
            ],
            options={
                'db_table': 'residue',
                'ordering': ['sequence_number'],
            },
        ),
    ]
