# Generated by Django 3.2.8 on 2022-01-13 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protein', '0004_domain_parent'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_ID', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'chain',
            },
        ),
        migrations.CreateModel(
            name='PDBData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdb', models.TextField()),
            ],
            options={
                'db_table': 'pdbdata',
            },
        ),
        migrations.CreateModel(
            name='StructureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'structure_type',
            },
        ),
        migrations.CreateModel(
            name='StructureDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.chain')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.domain')),
                ('pdbdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.pdbdata')),
            ],
            options={
                'db_table': 'structure_domain',
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdb_code', models.CharField(max_length=4, unique=True)),
                ('publication_date', models.DateField()),
                ('resolution', models.DecimalField(decimal_places=3, max_digits=5)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.publication')),
                ('structure_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.structuretype')),
            ],
            options={
                'db_table': 'structure',
            },
        ),
        migrations.AddField(
            model_name='chain',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.structure'),
        ),
    ]
