# Generated by Django 3.2.8 on 2022-02-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='resolution',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
    ]
