# Generated by Django 3.2.8 on 2022-03-24 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_auto_20220324_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chain', to='structure.structure'),
        ),
        migrations.AlterField(
            model_name='structuredomain',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_domain', to='structure.chain'),
        ),
    ]
