# Generated by Django 3.2.8 on 2021-10-22 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latin_name', models.CharField(max_length=100, unique=True)),
                ('common_name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'species',
            },
        ),
        migrations.CreateModel(
            name='ProteinFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protein.proteinfamily')),
            ],
            options={
                'db_table': 'protein_family',
            },
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_name', models.SlugField(max_length=100, unique=True)),
                ('accession', models.CharField(db_index=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=200)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.proteinfamily')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protein.protein')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.species')),
            ],
            options={
                'db_table': 'protein',
            },
        ),
        migrations.CreateModel(
            name='Isoform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(db_index=True, max_length=100, null=True)),
                ('sequence', models.TextField()),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.protein')),
            ],
            options={
                'db_table': 'protein_isoform',
            },
        ),
    ]
