# Generated by Django 3.2.8 on 2021-10-28 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProteinState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'protein_state',
            },
        ),
        migrations.CreateModel(
            name='ProteinConformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isoform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.isoform')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.proteinstate')),
            ],
            options={
                'db_table': 'protein_conformation',
                'ordering': ('id',),
            },
        ),
    ]
