# Generated by Django 3.2.8 on 2021-11-12 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0002_proteinconformation_proteinstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'protein_domaintype',
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.TextField()),
            ],
            options={
                'db_table': 'sequence',
            },
        ),
        migrations.RemoveField(
            model_name='isoform',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='proteinconformation',
            name='isoform',
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.domaintype')),
                ('isoform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.isoform')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protein.sequence')),
            ],
            options={
                'db_table': 'protein_domain',
            },
        ),
        migrations.AddField(
            model_name='proteinconformation',
            name='domain',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='protein.domain'),
            preserve_default=False,
        ),
    ]
