# Generated by Django 3.2.8 on 2021-11-19 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protein', '0003_auto_20211112_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protein.domain'),
        ),
    ]
