# Generated by Django 3.2.8 on 2022-01-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('authors', models.TextField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('reference', models.TextField(null=True)),
            ],
            options={
                'db_table': 'publication',
            },
        ),
    ]
