# Generated by Django 3.2.8 on 2022-02-08 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'journal',
            },
        ),
        migrations.CreateModel(
            name='WebResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.TextField()),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'web_resource',
            },
        ),
        migrations.CreateModel(
            name='WebLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.TextField()),
                ('web_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.webresource')),
            ],
            options={
                'db_table': 'web_link',
            },
        ),
        migrations.AlterField(
            model_name='publication',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.journal'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.weblink'),
        ),
    ]
