# Generated by Django 3.2.8 on 2022-01-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residue',
            name='amino_acid_three_letter',
            field=models.CharField(default=None, max_length=3),
            preserve_default=False,
        ),
    ]
